# Generated by Django 5.1.3 on 2024-12-08 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ML', 'Milk'), ('CR', 'Curd'), ('LS', 'Lassi'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('CZ', 'Cheese'), ('IC', 'Ice_Creams')], max_length=2),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('locality', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Chittragram', 'Chittragram'), ('Khulna', 'Khulna'), ('Barishal', 'Barishal'), ('Jessore', 'Jessore'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Gopalganj', 'Gopalganj'), ('Faridpur', 'Madaripur'), ('Madaripur', 'Faridpur'), ('Bagherhat', 'Bagherhat'), ('Kotalipara', 'Kotalipara')], max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
